name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'gui/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'gui/package-lock.json'

      - name: Install Dependencies
        run: |
          cd gui
          npm ci

      - name: Build
        run: |
          cd gui
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gui/dist